### ISSUE TITLE
Question: Is this signer being maintained?

### ISSUE THREAD

**Issue by knd** [lattejed/tezos-azure-hsm-signer#2]
I'm curious if this signer is still working today, compatible with tezos node in 2020. 

Specifically: https://tezos.gitlab.io/releases/version-7.html

**Comment by peterlayke** [comment]
Hi just wondering on the hardware specs for the signer. I assume it's just a low spec machine that is needed?

**Comment by lattejed** [comment]
No longer being maintained. Feel free to fork. Originally developed for the lowest tier on Azure.
